### ISSUE TITLE
Feedback on documentation 

### ISSUE THREAD

**Issue by anushkadesai077** [BigDataIA-Spring2023-Team-07/Assignment_02#10]
Excellent & thorough documentation overall. Just a couple of suggestions/feedbacks: 

1. You forgot to add a link to the Airflow instance (if it is live)
2. Code lab document - could have started off with an overview or introduction about what the project is and the group members names and any/all application links to add more value to this code lab document. Starting off with an architectural diagram right away seems ambiguous for a new reader

**Comment by shu3hamiitkgp** [comment]
Thanks for the feedback, I agree; we'll update the code lab documentation to make it more intuitive. Airflow is active, but we didn't add it as it would require credentials to login. We'll provide that separately to you offline
